# coding: utf-8

"""
    DeepAPI

    Our AI API service offers a seamless and efficient solution for businesses and individuals seeking to leverage the power of artificial intelligence without the complexity and cost of managing their infrastructure. By choosing DeepAPI, you eliminate the need to invest in and maintain expensive servers and GPUs, as we provide a robust, scalable, cloud-based platform operating out of multiple data centers that ensures high performance, low latency and reliability. Our on-demand service allows you to pay only for what you use, ensuring a cost-effective approach to accessing cutting-edge AI capabilities. Get your API key today at https://deepapi.ai

    The version of the OpenAPI document: 1.0.0
    Contact: contact@deepapi.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deep_api.api.text_api import TextApi


class TestTextApi(unittest.TestCase):
    """TextApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TextApi()

    def tearDown(self) -> None:
        pass

    def test_analyze_sentiment(self) -> None:
        """Test case for analyze_sentiment

        Analyzes the sentiment of the input text.
        """
        pass

    def test_chat(self) -> None:
        """Test case for chat

        Generate chat-like responses using an LLM (Large Language Model) which can perform a wide variety of tasks.
        """
        pass

    def test_detect_language(self) -> None:
        """Test case for detect_language

        Detects the language of the input text.
        """
        pass

    def test_translate_text(self) -> None:
        """Test case for translate_text

        Translates the input text into the target language.
        """
        pass


if __name__ == '__main__':
    unittest.main()
